PAYMENT_METHODS_MAPPING = {
    "Credit": "Credit",
    "WIC": "WIC",
    "WICcash": "WIC Cash",
    "SFMNP": "Senior Farmers Market Nutrition Program",
    "SNAP": "SNAP (Food Stamps)",
}

PRODUCTS_MAPPING = {
    "Organic": "Organic",
    "Bakedgoods": "Baked Goods",
    "Cheese": "Cheese",
    "Crafts": "Crafts",
    "Flowers": "Flowers",
    "Eggs": "Eggs",
    "Seafood": "Seafood",
    "Herbs": "Herbs",
    "Vegetables": "Vegetables",
    "Honey": "Honey",
    "Jams": "Jams",
    "Maple": "Maple",
    "Meet": "Meet",
    "Nursery": "Nursery",
    "Nuts": "Nuts",
    "Plants": "Plants",
    "Poultry": "Poultry",
    "Prepared": "Prepared",
    "Soap": "Soap",
    "Trees": "Trees",
    "Wine": "Wine",
    "Coffee": "Coffee",
    "Beans": "Beans",
    "Fruits": "Fruits",
    "Grains": "Grains",
    "Juices": "Juices",
    "Mushrooms": "Mushrooms",
    "PetFood": "Pet Food",
    "Tofu": "Tofu",
    "WildHarvested": "WildHarvested"
}